### ISSUE TITLE
midi信息页会在排行榜加载出来前显示上一个midi的排行榜

### ISSUE THREAD

**Issue by YangQwQ** [DotLab/TouhouMix#14]
当网络状况不佳时，midi信息界面会在此midi的排行榜加载出来之前加载上一个加载出来的排行榜，就算网络很好，在进入下一个midi时也会显示一小段时间的上一个排行榜

虽然这可能不是什么大问题，不过希望能在加载出排行榜前显示一个loading图标而不是上一个midi的排行榜

**Comment by Kailang** [comment]
Clear items before fetching in a28c0e213d5258f5c74d8b8c1401cf87204448a6
